image: maven

stages:
    - build
    - test

build:
    stage: build
    script:
        - mvn install
    tags: [docker-atp]

test:
    stage: test
    script:
    - mvn test
    tags: [docker-atp]
